---
  - name: "generic playbook"
    hosts: localhost
    connection: local 


    tasks:

      - name: download node14
        get_url:
          url: https://nodejs.org/dist/v16.13.2/node-v16.13.2-linux-x64.tar.xz
          dest: /tmp/node-v16.13.2-linux-x64.tar.xz
          mode: '0444'
      - name: unpack node14
        shell: "tar xf /tmp/node-v17.4.0-linux-x64.tar.xz --directory {{ansible_env.HOME}}"
      - name: PATH
        ansible.builtin.lineinfile:
          path: "{{ansible_env.HOME}}/.bashrc"
          regexp: '^export PATH=$HOME/node-v16.13.2-linux-x64/bin:$PATH'
          line: export PATH=$HOME/node-v16.13.2-linux-x64/bin:$PATH
          state: present

## ----------------------
