---
  - name: "generic playbook"
    hosts: localhost
    connection: local 

    


    tasks:
      - name: delete node14
        file:
          path="{{ansible_env.HOME}}/node-v16.13.2-linux-x64"
          state=absent
      - name: PATH
        ansible.builtin.lineinfile:
          path: "{{ansible_env.HOME}}/.bashrc"
          regexp: '^export PATH=$HOME/node-v16.13.2-linux-x64/bin:$PATH'
          line: export PATH=$HOME/node-v16.13.2-linux-x64/bin:$PATH
          state: absent
